SELECT owner, COUNT(*) AS table_count
FROM all_tables 
WHERE owner NOT IN (
  'SYS','SYSTEM','OUTLN','DBSNMP','APPQOSSYS','GSMADMIN_INTERNAL',
  'XDB','WMSYS','CTXSYS','MDSYS','ORDSYS','ORDDATA','OLAPSYS',
  'LBACSYS','SYSMAN','EXFSYS','MGMT_VIEW','FLOWS_FILES','APEX_040000',
  'APEX_PUBLIC_USER','ANONYMOUS','XS$NULL','ORACLE_OCM','DIP'
)
GROUP BY owner
ORDER BY table_count DESC;